### ISSUE TITLE
explain more and redmine 5.0?

### ISSUE THREAD

**Issue by ashrafalzyoud** [xmera-circle/redmine_computable_custom_field#1]
Can you explain more about how it works with pictures?

**Comment by liaham** [comment]
Did you visit https://circle.xmera.de/projects/redmine-computable-custom-field/wiki/Wiki?

There are screenshots and a small documentation.

**Comment by ashrafalzyoud** [comment]
It's working in redmine 5.0?!?

**Comment by liaham** [comment]
No, it won't work out of the box.  

I am planning to support Redmine 5.x within the next 4 or 5 months.  Maybe it is possible for you to make the required adaptions earlier and send a pull request?
